### ISSUE TITLE
Keep the random guest name?

### ISSUE THREAD

**Issue by aiueoH** [GeorgioWan/oPartTime#1]
Now, the random guest name change when switch different pages. I think it should be kept or the guest will feel strange why has different calls. :confused:

**Comment by GeorgioWan** [comment]
I found this problem this morning !!
I'm develop location(city and district) now, maybe solve this problem late :smoking:

**Comment by aiueoH** [comment]
Nice cigarette :smoking:

**Comment by aiueoH** [comment]
I solved this problem in just and create the pull request.

I use javascript to update cookie expire every minute to make it keep the random guest name. To access cookie in javascript, i add the gem - [js_cookie_rails](https://github.com/freego/js_cookie_rails) into this project.

**Comment by GeorgioWan** [comment]
GOOOOOOOOOOOOOOD JOB!!!!
好 [cookies](https://github.com/freego/js_cookie_rails) 不吃嗎？ :cookie:
