### ISSUE TITLE
 About city and district selector

### ISSUE THREAD

**Issue by GeorgioWan** [GeorgioWan/oPartTime#10]
_請教，在選擇縣市後可以選擇鄉鎮市區這個功能。_
#### 第一個問題討論
- 目前已經作好一版是用 js 動態替換鄉鎮市區，
  但這樣每次選擇縣市時 ajax 就得送出一次 get，不知道是否有什麼影響？
  (此方法讓我不知道怎麼抓到每一區的工作貼文數量)
- 對此，我有第二個想法是這樣子的，
  直接把全部的鄉鎮市區 html 生完，再用[頁籤](http://getbootstrap.com/javascript/#tabs)的方式切換，
  但我想這樣會在第一次 load page 時需要耗費比較多的時間(?)。
  (此方法我知道怎麼抓到每一區的工作貼文數量)
#### 第二個問題討論
- 是不是選擇完區域後，要直接更新 list，而不是整個網頁阿...?
  要這樣感覺又很麻煩QQ

**Comment by aiueoH** [comment]
第一個問題，送出 get 我覺得影響不大，但我比較喜歡預載的方式，除非真的 load page 時耗費太多時間(我猜是不會差多少啦)。

第二個問題，目前看起來似乎是有 turbolink，如果你強調的是那個感覺，那用 ajax 來抽換 list 應該是比較好(順暢、漂亮)，不過網址就不會變動，有時候網址會動還蠻重要的，使用者可以分享這個網址

另外，我覺得在點選縣市後還要選鄉鎮區才能顯示工作不太好

**Comment by GeorgioWan** [comment]
**第一個問題**換成預載的方式解決。
**第二個問題**暫時就先這樣。

「另外」的部分，由於想不到什麼好流程，所以作成了兩種選擇方式：
- **地圖**拿來選大區域(縣市)
- **文字選擇**拿來選小區域(縣市 -> 鄉鎮市區)
