### ISSUE TITLE
What the hell problem in iOS 9 !!!

### ISSUE THREAD

**Issue by GeorgioWan** [GeorgioWan/oPartTime#31]
在 iOS 9 的環境中，對於 font-family 的 fetch 不知道變動為何，導致指定的字型部分無法正常顯示

**Comment by GeorgioWan** [comment]
真的很奇怪！iOS 9 以下裝置與其他 mobile 裝置皆沒問題...
唯獨 iOS 9 對於 font-family 使用 [**cwTeXHei**](https://www.google.com/fonts/earlyaccess) 有問題

p.s. 目前暫時用微軟正黑體解 https://github.com/GeorgioWan/oPartTime/pull/32

**Comment by aiueoH** [comment]
hell from the other side

**Comment by GeorgioWan** [comment]
#### 在了解 **assets pipeline** 後，推測問題在於 `@import` 的順序問題

原本未整理的 `application.css.scss` 中使用了 

``` sass
*= require_tree .
*= require self
```

如此的話，會先載入其他 assets 的 css、 scss 後，才載入 `application.css.scss` 本身，
而 `@import` 和 `@font-face` 又是寫在 `application.css.scss` 中，
編譯後因順序問題，導致 `fonts-family` 發生錯誤，至於為何只有 iOS 9 有問題就不得而知了！

> 目前已將 `application.css.scss` 改成逐個 `@import` 的方式 (較佳 - _自己的順序自己排_)
> [Way here](https://github.com/GeorgioWan/oPartTime/commit/0a32bba7e469e90961b44770a84a00abf5e17a4d)
